org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx4096M"
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35

# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M
kotlin.native.ignoreDisabledTargets=true

# Compose
org.jetbrains.compose.experimental.wasm.enabled=true
